"""
Reads the Lead Tracker spreadsheet and exports live stats to a JS file
that the virtual office loads.
"""
import json
from datetime import datetime
from openpyxl import load_workbook

TRACKER_PATH = r'C:\Users\trisd\clawd\data\Valencia-Lead-Tracker.xlsx'
OUTPUT_PATH = r'C:\Users\trisd\clawd\office\live-data.js'

def sync():
    try:
        wb = load_workbook(TRACKER_PATH, data_only=True)
    except FileNotFoundError:
        write_empty()
        return
    
    ws = wb["Lead Tracker"]
    
    leads = []
    total = 0
    new_count = 0
    contacted = 0
    consultation = 0
    quote_sent = 0
    won = 0
    lost = 0
    no_response = 0
    pipeline_value = 0
    won_value = 0
    
    by_source = {}
    by_category = {}
    recent_leads = []
    
    for row in range(3, 503):
        date_val = ws[f'B{row}'].value
        if date_val is None:
            break
        
        total += 1
        source = ws[f'C{row}'].value or "Unknown"
        category = ws[f'D{row}'].value or "Other"
        client = ws[f'E{row}'].value or ""
        location = ws[f'H{row}'].value or ""
        description = ws[f'I{row}'].value or ""
        est_value = ws[f'J{row}'].value or 0
        priority = ws[f'K{row}'].value or ""
        status = ws[f'L{row}'].value or "New"
        notes = ws[f'P{row}'].value or ""
        
        if isinstance(est_value, str):
            try:
                est_value = int(est_value.replace('$','').replace(',',''))
            except:
                est_value = 0
        
        # Count statuses
        if status == "New": new_count += 1
        elif status == "Contacted": contacted += 1
        elif status == "Consultation Scheduled": consultation += 1
        elif status == "Quote Sent": quote_sent += 1
        elif status == "Won": won += 1
        elif status == "Lost": lost += 1
        elif status == "No Response": no_response += 1
        
        # Pipeline = everything active (not won/lost/no response/not qualified)
        if status not in ["Won", "Lost", "No Response", "Not Qualified"]:
            pipeline_value += est_value
        
        if status == "Won":
            won_value += est_value
        
        # By source
        by_source[source] = by_source.get(source, 0) + 1
        
        # By category
        by_category[category] = by_category.get(category, 0) + 1
        
        # Recent leads (last 10)
        if total <= 10:
            date_str = ""
            if isinstance(date_val, datetime):
                date_str = date_val.strftime("%m/%d")
            recent_leads.append({
                "date": date_str,
                "source": source,
                "category": category,
                "description": description[:60],
                "location": location,
                "value": est_value,
                "status": status,
                "priority": priority
            })
    
    close_rate = (won / total * 100) if total > 0 else 0
    avg_deal = (won_value / won) if won > 0 else 0
    
    data = {
        "lastSync": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "totalLeads": total,
        "newLeads": new_count,
        "contacted": contacted,
        "consultations": consultation,
        "quotesSent": quote_sent,
        "won": won,
        "lost": lost,
        "noResponse": no_response,
        "pipelineValue": pipeline_value,
        "wonValue": won_value,
        "closeRate": round(close_rate, 1),
        "avgDeal": round(avg_deal),
        "bySource": by_source,
        "byCategory": by_category,
        "recentLeads": recent_leads
    }
    
    js_content = f"// Auto-generated by sync-office-data.py — DO NOT EDIT\n"
    js_content += f"// Last sync: {data['lastSync']}\n"
    js_content += f"window.LIVE_DATA = {json.dumps(data, indent=2)};\n"
    
    with open(OUTPUT_PATH, 'w', encoding='utf-8') as f:
        f.write(js_content)
    
    print(f"Synced: {total} leads, ${pipeline_value} pipeline, ${won_value} won")

def write_empty():
    data = {
        "lastSync": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "totalLeads": 0, "newLeads": 0, "contacted": 0,
        "consultations": 0, "quotesSent": 0, "won": 0, "lost": 0,
        "noResponse": 0, "pipelineValue": 0, "wonValue": 0,
        "closeRate": 0, "avgDeal": 0,
        "bySource": {}, "byCategory": {}, "recentLeads": []
    }
    js_content = f"window.LIVE_DATA = {json.dumps(data, indent=2)};\n"
    with open(OUTPUT_PATH, 'w', encoding='utf-8') as f:
        f.write(js_content)
    print("No tracker found — wrote empty data")

if __name__ == "__main__":
    sync()
