// Auto-generated by sync-office-data.py — DO NOT EDIT
// Last sync: 2026-03-05 12:22:31
window.LIVE_DATA = {
  "lastSync": "2026-03-05 12:22:31",
  "totalLeads": 85,
  "newLeads": 85,
  "contacted": 0,
  "consultations": 0,
  "quotesSent": 0,
  "won": 0,
  "lost": 0,
  "noResponse": 0,
  "pipelineValue": 0,
  "wonValue": 0,
  "closeRate": 0.0,
  "avgDeal": 0,
  "bySource": {
    "Reddit - r/chicago": 1,
    "Reddit - r/ChicagoSuburbs": 2,
    "Reddit - r/HomeImprovement": 14,
    "Reddit - r/homeowners": 16,
    "Nextdoor": 1,
    "Facebook": 51
  },
  "byCategory": {
    "Other": 62,
    "Commercial": 1,
    "Painting": 2,
    "Bathroom Remodel": 1,
    "Tile": 1,
    "Flooring": 4,
    "Handyman": 2,
    "Basement": 2,
    "Deck/Patio": 3,
    "Electrical": 2,
    "Plumbing": 3,
    "Drywall": 1,
    "Full Renovation": 1
  },
  "recentLeads": [
    {
      "date": "02/27",
      "source": "Reddit - r/chicago",
      "category": "Other",
      "description": "Anyone else getting billed by RCN/Astound when they never si",
      "location": "Chicago",
      "value": 0,
      "status": "New",
      "priority": "\u2744\ufe0f Cold"
    },
    {
      "date": "02/27",
      "source": "Reddit - r/ChicagoSuburbs",
      "category": "Other",
      "description": "Deep Cleaners on North Shore? \u2014 Hi all!\n\nLooking for recomme",
      "location": "Chicago",
      "value": 0,
      "status": "New",
      "priority": "\u26a1 Warm"
    },
    {
      "date": "02/27",
      "source": "Reddit - r/ChicagoSuburbs",
      "category": "Other",
      "description": "Custom home allowances \u2014 Has anyone here built a custom home",
      "location": "Chicago",
      "value": 0,
      "status": "New",
      "priority": "\u2744\ufe0f Cold"
    },
    {
      "date": "02/27",
      "source": "Reddit - r/HomeImprovement",
      "category": "Commercial",
      "description": "Should spray texture rub off? \u2014 I had a contractor rip out s",
      "location": "Chicago",
      "value": 0,
      "status": "New",
      "priority": "\u26a1 Warm"
    },
    {
      "date": "02/27",
      "source": "Reddit - r/HomeImprovement",
      "category": "Painting",
      "description": "Trouble matching my paints to Dunn Edward\u2019s \u2014 I have selecte",
      "location": "Chicago",
      "value": 0,
      "status": "New",
      "priority": "\u2744\ufe0f Cold"
    },
    {
      "date": "02/27",
      "source": "Reddit - r/HomeImprovement",
      "category": "Bathroom Remodel",
      "description": "Florida bathroom reno - tub/shower against concrete wall and",
      "location": "Chicago",
      "value": 0,
      "status": "New",
      "priority": "\u2744\ufe0f Cold"
    },
    {
      "date": "02/27",
      "source": "Reddit - r/HomeImprovement",
      "category": "Other",
      "description": "Ice Damming? \u2014 Looking for some guidance here. I have a 1960",
      "location": "Chicago",
      "value": 0,
      "status": "New",
      "priority": "\ud83d\udd25 Hot"
    },
    {
      "date": "02/27",
      "source": "Reddit - r/HomeImprovement",
      "category": "Other",
      "description": "Ye olde popcorn ceiling an asbestos anxiety \u2014 Hey all, thank",
      "location": "Chicago",
      "value": 0,
      "status": "New",
      "priority": "\u2744\ufe0f Cold"
    },
    {
      "date": "02/27",
      "source": "Reddit - r/HomeImprovement",
      "category": "Tile",
      "description": "Stone Accent Wall Basement \u2014 Hi all;\n\nLooking for advice\n\nWe",
      "location": "Chicago",
      "value": 0,
      "status": "New",
      "priority": "\u26a1 Warm"
    },
    {
      "date": "02/27",
      "source": "Reddit - r/HomeImprovement",
      "category": "Flooring",
      "description": "Window with soft Wood \u2014 My window has a vinyl covering over ",
      "location": "Chicago",
      "value": 0,
      "status": "New",
      "priority": "\u2744\ufe0f Cold"
    }
  ]
};
